// @ts-nocheck - auto-generated by Soroban CLI, do not edit manually
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CBADFNON7JOPM3XK5DBEILJF4U4DT3KLWUSVJIGZUA3QBEKQD6GBJI3O",
  }
} as const


export interface Poll {
  id: u64;
  option_a: string;
  option_b: string;
  question: string;
  votes_a: u64;
  votes_b: u64;
}

export interface Client {
  /**
   * Construct and simulate a get_polls transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_polls: (options?: MethodOptions) => Promise<AssembledTransaction<Array<Poll>>>

  /**
   * Construct and simulate a vote_poll transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  vote_poll: ({id, choice}: {id: u64, choice: u32}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a create_poll transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  create_poll: ({question, option_a, option_b}: {question: string, option_a: string, option_b: string}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a delete_poll transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  delete_poll: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  public readonly options: ContractClientOptions;

  constructor(options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAQAAAAAAAAAAAAAABFBvbGwAAAAGAAAAAAAAAAJpZAAAAAAABgAAAAAAAAAIb3B0aW9uX2EAAAAQAAAAAAAAAAhvcHRpb25fYgAAABAAAAAAAAAACHF1ZXN0aW9uAAAAEAAAAAAAAAAHdm90ZXNfYQAAAAAGAAAAAAAAAAd2b3Rlc19iAAAAAAY=",
        "AAAAAAAAAAAAAAAJZ2V0X3BvbGxzAAAAAAAAAAAAAAEAAAPqAAAH0AAAAARQb2xs",
        "AAAAAAAAAAAAAAAJdm90ZV9wb2xsAAAAAAAAAgAAAAAAAAACaWQAAAAAAAYAAAAAAAAABmNob2ljZQAAAAAABAAAAAEAAAAQ",
        "AAAAAAAAAAAAAAALY3JlYXRlX3BvbGwAAAAAAwAAAAAAAAAIcXVlc3Rpb24AAAAQAAAAAAAAAAhvcHRpb25fYQAAABAAAAAAAAAACG9wdGlvbl9iAAAAEAAAAAEAAAAQ",
        "AAAAAAAAAAAAAAALZGVsZXRlX3BvbGwAAAAAAQAAAAAAAAACaWQAAAAAAAYAAAABAAAAEA==" ]),
      options
    )
    this.options = options;
  }
  public readonly fromJSON = {
    get_polls: this.txFromJSON<Array<Poll>>,
        vote_poll: this.txFromJSON<string>,
        create_poll: this.txFromJSON<string>,
        delete_poll: this.txFromJSON<string>
  }
}
